urls.py
from django.conf.urls import patterns, url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import login
from django.contrib import admin
from django.conf import settings
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.core.urlresolvers import reverse
from django.utils.functional import curry
from django.views.defaults import *
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from app.api import *
from tastypie.api import Api
from calendario.urls import *

admin.autodiscover()

v1_api = Api(api_name='v1')
v1_api.register(AvaluoResource())
v1_api.register(UserResource())
v1_api.register(DeptoResource())
v1_api.register(ImagenAvaluoResource())
v1_api.register(EstadisticoAsignaResource())
v1_api.register(EventoResource())
v1_api.register(EventoCalendarioResource())
v1_api.register(FacturaResource())
    # Examples:
    # url(r'^$', 'SIAV.views.home', name='home'),
    #url(r'^SIAV/', include('SIAV.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:

    # Upload files Urls

handler404 = 'app.views.handler404'
handler500 = 'app.views.handler500'
handler401 = 'app.views.handler401'
urlpatterns = patterns(


    '', url(r'^SIAV/ajax_upload/(\w*\d+)/(\@*\w*\d+)/$', 'app.uploads.ajax_upload', name="ajax_upload"),

    url(r'^oauth2/', include('provider.oauth2.urls', namespace = 'oauth2')),
    #url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^api/', include(v1_api.urls)),
    url(r'^SIAV/admin/', include(admin.site.urls)),



    #Urls del SIAV

    url(r'^SIAV/$', 'app.views.home', name='home'),
    url(r'^SIAV/login/$',  login),
    url(r'^SIAV/logout/$', 'app.views.logout_view', name='logout_view'),
    url(r'^SIAV/home/$', 'app.views.home', name='home'),


    url(r'^SIAV/cambia_estatus/(?P<match>.+)/$', 'app.views.cambia_estatus', name='cambia_estatus'),

    #url(r'^$', 'app.views.lista_avaluo', name = 'lista_avaluo'),
    url(r'^SIAV/guarda_master/?(\d+)/?$', 'app.views.guarda_master', name='guarda_master'),
    url(r'^SIAV/consulta_master/', 'app.views.consulta_master', name='consulta_master'),
    url(r'^SIAV/consulta_master/(?P<query>)/?$', 'app.views.consulta_master', name='consulta_master'),

    #Consulta de comparables
    url(r'^SIAV/consulta_comparable/$', 'app.views.consulta_comparable', name='consulta_comparable'),
    url(r'^SIAV/consulta_comparable/(?P<query>)/?$', 'app.views.consulta_comparable', name='consulta_comparable'),


    #url(r'^SIAV/consulta_sencilla/', 'app.views.consulta_sencilla', name='consulta_sencilla'),
    url(r'^SIAV/respuesta_consulta_sencilla/?(\d+)/?$', 'app.views.respuesta_consulta_sencilla', name='respuesta_consulta_sencilla'),

    url(r'^SIAV/alta_avaluo/$', 'app.views.alta_avaluo', name='alta_avaluo'),
    url(r'^SIAV/alta_avaluo_paquete/$', 'app.views.alta_avaluo_paquete', name='alta_avaluo_paquete'),
    url(r'^SIAV/actualiza_avaluo/(\d+)/$', 'app.views.actualiza_avaluo', name='actualiza_avaluo'),

    url(r'^SIAV/visita/$', 'app.views.visita', name='visita'),
    url(r'^SIAV/edita_visita/(\d+)/$', 'app.views.edita_visita', name='edita_visita'),

    #Url para eventos masivos
    url(r'^SIAV/visita_masiva/$', 'app.views.visita_masiva', name='visita_masiva'),
    url(r'^SIAV/captura_masiva/$', 'app.views.captura_masiva', name='captura_masiva'),
    url(r'^SIAV/salida_masiva/$', 'app.views.salida_masiva', name='salida_masiva'),

    url(r'^SIAV/show_visita_pdf/(\d+)/$', 'app.views.show_visita_pdf', name='show_visita_pdf'),
    url(r'^SIAV/show_orden_visita/$', 'app.views.show_orden_visita', name='show_orden_visita'),
    url(r'^SIAV/show_orden_visita/(?P<avaluo_visitado>)/?$', 'app.views.show_orden_visita', name='show_orden_visita'),

    url(r'^SIAV/captura/$', 'app.views.captura', name='captura'),

    #Salida
    url(r'^SIAV/salida/$', 'app.views.salida', name='salida'),
    url(r'^SIAV/edita_salida/(\d+)/$', 'app.views.edita_salida', name='edita_salida'),
    #url(r'^SIAV/salida_efectiva/(\d+)/$', 'app.views.salida_efectiva', name='salida_efectiva'),

    #Alta Usuario
    url(r'^SIAV/alta_usuario/$', 'app.views.alta_usuario', name='alta_usuario'),
    url(r'^SIAV/lista_usuario/$', 'app.views.lista_usuario', name='lista_usuario'),

    url(r'^SIAV/lista_valuador/$', 'app.views.lista_valuador', name='lista_valuador'),

    url(r'^SIAV/mapas/$', 'app.views.mapas', name='mapas'),

    url(r'^SIAV/facturar/$', 'app.views.facturar', name='facturar'),

    url(r'^SIAV/liquidar/$', 'app.views.liquidar', name='liquidar'),

    url(r'^SIAV/estadistico_anio_js/$', 'app.views.estadistico_anio_js', name='estadistico_anio_js'),
    url(r'^SIAV/estadistico/(\d+)/(\d+)/$', 'app.views.estadistico', name='estadistico'),
    url(r'^SIAV/estadistico_cliente_depto/(\d+)/(\d+)/$', 'app.views.estadistico_cliente_depto', name='estadistico_cliente_depto'),
    #url(r'^SIAV/estadistico/', 'app.views.estadistico', name = 'estadistico'),
    url(r'^SIAV/realtime/$', 'app.views.realtime', name = 'realtime'),

    #url(r'^SIAV/submitted/', 'app.views.submitted', name='submitted'),

    url(r'^SIAV/test/$', 'app.views.test', name='submitted'),

    url(r'^api/get_colonias/$', 'app.views.get_colonias', name='get_colonias'),
    url(r'^api/get_municipios/$', 'app.views.get_municipios', name='get_municipios'),
    url(r'^api/get_deptos/$', 'app.views.get_deptos', name='get_deptos'),
    url(r'^api/get_visitadores/$', 'calendario.views.get_visitadores', name='get_visitadores'),

    url(r'^SIAV/media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    #url(r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': '/static/img/favicon.ico'}),

    #Url para eliminar imagen
    url(r'^SIAV/elimina_imagen_captura/(\d+)/(\d+)/$', 'app.views.elimina_imagen_captura', name='elimina_imagen_captura'),

    #Urls del sitio web
    url(r'^$', 'website.views.index', name='index'),
    url(r'^faq/$', 'website.views.faq', name='faq'),
    url(r'^servicios/$', 'website.views.servicios', name='servicios'),
    url(r'^contacto/$', 'website.views.contacto', name='contacto'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'media/'}),

    #Urls del sitio movil
    #url(r'^SIAV/mobile/', 'app.views.mobile', name='mobile'),

    url(r'^swf/', 'app.views.swf', name='swf'),
)

    #Urls para sockets
urlpatterns += patterns('',
    url(r'^SIAV/chat/', 'websock.views.home', name='home'),
    url(r'^get_notificaciones/', 'websock.views.get_notificaciones', name='get_notificaciones'),
    url(r'^get_tolerancia/', 'websock.views.get_tolerancia', name='get_tolerancia'),
    url(r'^get_proceso/', 'websock.views.get_proceso', name='get_proceso'),
    url(r'^notificaciones_ind/', 'websock.views.notificaciones_ind', name='notificaciones_ind'),
    url(r'^get_conversaciones/', 'websock.views.get_conversaciones', name='get_conversaciones'),
    url(r'^chat_leido/(\d+)/$', 'websock.views.chat_leido', name='chat_leido'),

    #url(r'^marca_leidos/', 'websock.views.marca_leidos', name='marca_leidos'),
    url(r'^node_api$', 'websock.views.node_api', name='node_api'),

    url(r'^monto_inline/', 'app.views.inline.monto_inline', name='monto_inline'),
    url(r'^factura_inline/', 'app.views.inline.factura_inline', name='factura_inline'),
    url(r"^SIAV/calendario/", include("calendario.urls")),

    #Urls de calendario
    #url(include(r'^calendario/',calendario.urls)),
)


# Add the static files pattern to the url.
urlpatterns += staticfiles_urlpatterns() 
# handler404 = 'app.views.errors.not_found_error'

app/forms.py
# -*- encoding: utf-8 -*-
import datetime
from app.models import *
from django import forms
from django.forms import ModelForm
from crispy_forms.helper import FormHelper, reverse
from crispy_forms.layout import *
from django.forms import fields, models, formsets, widgets


SERVICIOS = (
    ('', 'N/D'),
    ('AVALUO  CREDITO HIPOTECARIO', 'AVALUO  CREDITO HIPOTECARIO'),
    ('AVALUO PARA JUICIO', 'AVALUO PARA JUICIO'),
    ('AVALUO PARA DACION EN PAGO', 'ESTIMACION POSICIONAMIENTO'),
    ('AVALUO  INFONAVIT PAQUETE', 'AVALUO  INFONAVIT PAQUETE'),
    ('AVALUO PARA REESTRUCTURA DE CREDITO', 'AVALUO PARA REESTRUCTURA DE CREDITO'),
    ('AVALUO PARTICULAR', 'AVALUO PARTICULAR'),
    ('DICTAMEN TECNICO  PUENTE', 'DICTAMEN TECNICO  PUENTE'),
    ('INSPECCION DE AVANCE DE OBRA', 'INSPECCION DE AVANCE DE OBRA'),
    ('AVALUO  INFONAVIT MERCADO ABIERTO', 'AVALUO INFONAVIT MERCADO ABIERTO'),
    ('ESTIMACION POR POSICIONAMIENTO', 'ESTIMACION POR POSICIONAMIENTO'),
    ('AVALUO TIPO  PUENTE', 'AVALUO TIPO  PUENTE'),
    ('DIFERENCIA', 'DIFERENCIA'),
    ('DICTAMEN TECNICO INFONAVIT', 'DICTAMEN TECNICO INFONAVIT'),
    ('AVALUO PYME', 'AVALUO PYME'),
    ('APOYO TECNICO', 'APOYO TECNICO'),
    ('AVALUO  DE LIQUIDEZ', 'AVALUO  DE LIQUIDEZ'),
    ('COFINAVIT', 'COFINAVIT'),
    ('COMPARECER EN JUZGADO', 'COMPARECER EN JUZGADO'),
    ('AVALUO CREDITO SIMPLE', 'AVALUO CREDITO SIMPLE'),
    ('AVALUO INFONAVIT RECUPERACION', 'AVALUO INFONAVIT RECUPERACION'),
    ('FOVISSTE', 'FOVISSTE'),
    ('INFONAVIT COFINANCIADO', 'INFONAVIT COFINANCIADO'),
    ('VERIFICACION DE GARANTIA 1480', 'VERIFICACION DE GARANTIA 1480'),
)

ESTATUS = (
    ('PROCESO', 'PROCESO'),
    ('DETENIDO', 'DETENIDO'),
    ('CONCLUIDO', 'CONCLUIDO'),
    ('CANCELADO', 'CANCELADO'),
)

ESTATUSV = (
    ('PROCESO', 'PROCESO'),
    ('DETENIDO', 'DETENIDO'),
    ('CANCELADO', 'CANCELADO'),
)

PRIORIDAD = (
    ('3', 'BAJA'),
    ('2', 'MEDIA'),
    ('1', 'ALTA'),
)

GRUPO = (
    ('-', ''),
    ('Admins', 'Admin'),
    ('Usuarios', 'Usuario'),
    ('Limitados', 'Limitados'),
)

MESES = (
    ('', ''),
    ('01', 'ENERO'),
    ('02', 'FEBRERO'),
    ('03', 'MARZO'),
    ('04', 'ABRIL'),
    ('05', 'MAYO'),
    ('06', 'JUNIO'),
    ('07', 'JULIO'),
    ('08', 'AGOSTO'),
    ('09', 'SEPTIEMBRE'),
    ('10', 'OCTUBRE'),
    ('11', 'NOVIEMBRE'),
    ('12', 'DICIEMBRE'),
)

ANIOS = (
    ('', ''),
    ('2010', '2010'),
    ('2011', '2011'),
    ('2012', '2012'),
    ('2013', '2013'),
    ('2014', '2014'),
)

class UserFullName(User):
    class Meta:
        proxy = True

    def __unicode__(self):
        return self.get_full_name()

class AltaAvaluo(ModelForm):

    Referencia = forms.CharField(required=False, label="Expediente Catastral")
    Calle = forms.CharField()
    NumExt = forms.CharField(label="Num. Ext.", required=False)
    NumInt = forms.CharField(label="Num. Int.", required=False)
    Colonia = forms.CharField()
    Tipo = forms.ModelChoiceField(queryset=Tipo.objects.filter(is_active='True'),label="Tipo de Bien")
    Municipio = forms.ModelChoiceField(queryset=Municipio.objects.filter(estado_id__is_active='True'))
    Estado = forms.ModelChoiceField(queryset=Estado.objects.filter(is_active='True'))
    Servicio = forms.ModelChoiceField(queryset=Servicio.objects.filter(is_active='True'),label="Tipo de Servicio")    
    Estatus = forms.ChoiceField(choices=ESTATUS)
    Prioridad = forms.ChoiceField(choices=PRIORIDAD)
    Depto = forms.ModelChoiceField(queryset=Depto.objects.filter(is_active='True'))
    Solicitud = forms.DateField(label="Fecha Solicitud", widget=forms.DateInput(format='%d/%m/%Y'),  input_formats=['%d/%m/%Y'])
    Lote_Tipo = forms.CharField(required=False)
    LatitudG = forms.DecimalField(required=False, label="Lon.G.")
    LatitudM = forms.DecimalField(required=False, label="Lon.M.",)
    LatitudS = forms.DecimalField(required=False, label="Lon.S.")
    LongitudG = forms.DecimalField(required=False, label="Lat.G.")
    LongitudM = forms.DecimalField(required=False, label="Lat.M.")
    LongitudS = forms.DecimalField(required=False, label="Lat.S.")  
    Observaciones = forms.CharField(widget=forms.Textarea, required=False)
    Valor = forms.DecimalField(required=False, widget=forms.TextInput())
    Valuador = forms.ModelChoiceField(queryset=UserFullName.objects.filter(groups__name='Valuadores'))
    Contacto = forms.ModelChoiceField(queryset=Contacto.objects.filter(is_active='True'),label="Contacto para visita",required=False)

    class Meta:
        model = Avaluo
        exclude = ('avaluo_id','Folio', 
                   'Visita','Gastos', 'Importe', 'Salida', 'Pagado', 'Factura', 'Prioridad','Valor_Construccion_Concluido','Valor_Terreno_Concluido','Factor_Terreno',
                   'Factor_Construccion','Valor_Mterreno','Valor_Mconstruccion','Declat','Declon' )
    def clean_Referencia(self):
        return self.cleaned_data['Referencia'] or None
    def __init__(self,  *args,  **kwargs):
        self.helper = FormHelper()
        self.helper.form_id = 'id-AltaAvaluo'
        self.helper.form_class = ''
        self.helper.form_method = 'post'
        self.helper.form_action = 'alta_avaluo'
        self.helper.layout = Layout(
            Div(
                Div(
                    'Alta Avaluo - Entrada',
                    'Referencia',
                    'Tipo',
                    'Calle',
                    'NumExt',
                    'NumInt',
                    'Estatus', css_class='col-md-3'),
                Div(
                    'Lote_Tipo',
                    'Colonia',
                    'Estado',
                    'Municipio',
                    'Contacto',
                    'Prioridad', css_class='col-md-3'),
                Div(
                    Div(
                        Div(Field('LatitudG',  css_class='col-md-20 input-small'),  css_class='col-md-4'),
                        Div(Field('LatitudM',  css_class='col-md-20 input-small'),  css_class='col-md-4'),
                        Div(Field('LatitudS',  css_class='col-md-20 input-small'),  css_class='col-md-4')),
                    Div(
                        Div(Field('LongitudG',  css_class='col-md-20 input-small'),  css_class='col-md-4'),
                        Div(Field('LongitudM',  css_class='col-md-20 input-small'),  css_class='col-md-4'),
                        Div(Field('LongitudS',  css_class='col-md-20 input-small'),  css_class='col-md-4')),
                    css_class='col-md-6'),
                Div(
                    'Servicio',
                    'Mterreno',
                    'Mconstruccion',
                    
                    'Cliente', css_class='col-md-3'),
                Div(
                    'Depto',
                    'Valuador',
                    'Valor',
                    'Solicitud',
                    css_class='col-md-3'),
                css_class='row-fluid'),
            'Observaciones',
            ButtonHolder(
                Submit('submit',  'Enviar',  css_class='btn-success')
            ))
        super(AltaAvaluo,  self).__init__(*args,  **kwargs)
        self.fields['Municipio'] = forms.ModelChoiceField(queryset=Municipio.objects.filter(estado_id__is_active='True'))
        self.fields['Depto'] = forms.ModelChoiceField(queryset=Depto.objects.filter(is_active='True'))


################################
## Plain 'ole Formset example ##
################################

class FormaSencillaPaquete(forms.Form):
    Referencia = forms.CharField(required=False, label="Expediente Catastral")
    # Calle = forms.CharField()
    NumExt = forms.CharField(label="Num. Ext.", required=False)
    NumInt = forms.CharField(label="Num. Int.", required=False)
    Colonia = forms.CharField()
    Tipo = forms.ModelChoiceField(required=True, label="Tipo Inmueble",  queryset=Tipo.objects.all())
    Municipio = forms.ModelChoiceField(queryset=Municipio.objects.filter(estado_id__is_active='True'))
    Estado = forms.ModelChoiceField(queryset=Estado.objects.filter(is_active='True'))
    Servicio = forms.ChoiceField(choices=SERVICIOS, label="Tipo Servicio")
    Estatus = forms.ChoiceField(choices=ESTATUS)
    Prioridad = forms.ChoiceField(choices=PRIORIDAD)
    Cliente = forms.ModelChoiceField(queryset=Cliente.objects.all())
    Depto = forms.ModelChoiceField(queryset=Depto.objects.filter(is_active='True'))
    Solicitud = forms.DateField(label="Fecha Solicitud", widget=forms.DateInput(format='%d/%m/%Y'),  input_formats=['%d/%m/%Y'])
    Observaciones = forms.CharField(widget=forms.Textarea, required=False)
    Valor = forms.DecimalField(required=False, widget=forms.TextInput())
    Valuador = forms.ModelChoiceField(queryset=Valuador.objects.filter(is_active='True'))

    class Meta:
        model = Avaluo
        exclude = ('avaluo_id', 'FolioK', 'LatitudG', 'LatitudM', 'LatitudS', 'LongitudG', 'LongitudM', 'LongitudS', 
                   'Mterreno', 'Mconstruccion', 'Visita', 'Gastos', 'Importe', 'Salida', 'Pagado', 'Factura','Declat','Declon',
                   'Referencia','NumExt','NumInt','Calle')
    def clean_Referencia(self):
        return self.cleaned_data['Referencia'] or None
    def __init__(self,  *args,  **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_tag = False
        self.helper.layout = Layout(
                        Div(
                            'Tipo',
                            'Servicio',
                            'Cliente',
                            css_class='col-md-3'),
                        Div(
                            'Depto',
                            'Colonia',
                            'Estado',
                            
                            css_class='col-md-3'),
                        Div(
                            'Municipio',
                            'Estatus',
                            'Prioridad',

                            css_class='col-md-3'),

app/templates/home/consultas/consulta_master.html
{% extends "home/base.html" %}

{% load listutil %}

{% load crispy_forms_tags %}

{% block consulta_master %}active{% endblock %}




 {% block style %}
 
     <style type="text/css" title="currentStyle">
    </style>

    <style>
      div.ui-datepicker{
    font-size:10px;
      }
    </style>
 
 {% endblock %}
 
 {% block script %}
    
    <script type="text/javascript" language="javascript" src="{{ STATIC_URL }}JS/jquery-datepicker-es.js"></script>
    <script type="text/javascript" language="javascript" src="{{ STATIC_URL }}JS/ajax_estados_municipios.js"></script> <!-- Incluye  sugerencia de colonias.-->

    
    <script type="text/javascript"> 
    
    $(document).ready( function() {
    var now = new Date();
    var month = (now.getMonth())+01;               
    var day = now.getDate();
    var year = now.getFullYear()
    if(month < 10) 
        month = "0" + month;
    if(day < 10) 
        day = "0" + day;
    var today = day + '/' + month + '/' + now.getFullYear() ;

    //$('#id_Mes>option:eq(' + month + ')').prop('selected', true);
    $("#id_Anio").val(year);
    });

    $(function() {

      $('#id_Solicitud').datepicker({ autoSize: true });
      $('#id_Inicial').datepicker({ autoSize: true });
      $('#id_Visita').datepicker({ autoSize: true });
      $('#id_Salida').datepicker({ autoSize: true });
      $('#id_Final').datepicker({ autoSize: true });


    $(":input").blur(function() {
    
    if(this.id != 'id_Observaciones') {
      this.value = this.value.toUpperCase();
      }
    });
      
    });
    
    </script>

<script type="text/javascript">
    $(document).ready(function () {
        $('#spinner').hide();
        $('#submit-id-submit').click(function () {
            foliok = $('#id_FolioK').val();
            ref = $('#id_Referencia').val();
            calle = encodeURIComponent($('#id_Calle').val());
            col = encodeURIComponent($('#id_Colonia').val());
            factura = encodeURIComponent($('#id_Factura').val());
            edo = $('#id_Estado').val();
            mun = $('#id_Municipio').val();
            cli = $('#id_Cliente').val();
            dep = $('#id_Depto').val();
            imp = $('#id_Importe').val();
            var allVals = [];
                     $('#id_estatus :checked').each(function() {
                       allVals.push($(this).val());
                     });
            val = encodeURIComponent($('#id_Valor').val());
            tipo = $('#id_Tipo').val();
            mes = $('#id_Mes').val();
            anio = $('#id_Anio').val();
            
            //$('#results').html('&nbsp;').load('/SIAV/consulta_master/?q1=' + q1);
            $('#results').html('&nbsp;').load('/SIAV/consulta_master/?foliok='+foliok+"&ref="+ref+"&calle="+calle+"&col="+col+"&edo="+edo+"&mun="+mun+"&factura="+factura+"&cli="+cli+"&dep="+dep+"&imp="+imp+"&val="+val+"&tipo="+tipo+"&mes="+mes+"&anio="+anio+"&est="+allVals);
        });
    });
        
    $(document).ajaxStart(function () {
        $('#spinner').show();
    }).ajaxStop(function () {
        $('#spinner').hide();
    });

</script>
    
 <script type="text/javascript" language="javascript" src="{{ STATIC_URL }}JS/mapas.js"></script>
    
      
{%endblock%}
    {% block script_bottom %}
    $("#id_Valor").autoNumeric('destroy');
    {% endblock %} 
{% block content %}


  <h1>Consulta</h1>
    <br>
      {% if forma.errors %}
        <p style="color: red;">
            Porfavor completa los campos faltantes.
        </p>
    {% endif %}

    {% crispy forma %}  
   <br>

  <div>
    <input id="submit-id-submit" type="submit" value="Buscar" class="btn btn-primary"/>
    <br/>
    <div class="margin table-responsive" align="center">
        <span id="spinner"><img src="{{ STATIC_URL }}spinner_large.gif"/ width="50px"></span>
        <div id='printableArea'><div id="results"></div></div>
    </div>
</div>

<script>
</script>
    
{% endblock %}

app/templates/home/consultas/consulta_sencilla.html
{% extends "home/base.html" %}

{% load listutil %}

{% load crispy_forms_tags %}

{% block consulta_sencilla %}active{% endblock %}

{% block style %}
 
     <style type="text/css" title="currentStyle">
    </style>
   
    <style>
      div.ui-datepicker{
	font-size:10px;
      }
    </style>
 
 {% endblock %}
 
 {% block script %}
	
    <script type="text/javascript" language="javascript" src="{{ STATIC_URL }}JS/jquery-datepicker-es.js"></script>
    <script type="text/javascript" language="javascript" src="{{ STATIC_URL }}JS/ajax_estados_municipios.js"></script> <!-- Incluye  sugerencia de colonias.-->

    <script type="text/javascript"> 
	
	$(document).ready( function() {
    var now = new Date();
    var month = (now.getMonth())+01;               
    var day = now.getDate();
    var year = now.getFullYear()
    if(month < 10) 
        month = "0" + month;
    if(day < 10) 
        day = "0" + day;
    var today = day + '/' + month + '/' + now.getFullYear();

    $('#id_Mes>option:eq(' + month + ')').prop('selected', true);
    $("#id_Anio").val(year);
	});

    $(function() {

	  $('#id_Solicitud').datepicker({ autoSize: true });

	$(":input").blur(function() {
	if(this.id != 'id_Observaciones') {
	  this.value = this.value.toUpperCase();
	  }
	});
	  
    });
    </script>
 {% endblock %}      

{% block content %}
  <h1>Consulta Sencilla</h1>
  <br />
      {% if forma.errors %}
        <p style="color: red;">
            Porfavor completa los campos faltantes.
        </p>
    {% endif %}
	{% crispy forma %}	
   <br>
{% endblock %}

app/templates/home/consultas/conversaciones.html
            {% for c in comments %}
            <div class="ui-chatbox-msg" style="display: block; max-width: 300px;">
            	<b>[{{c.date|date:"h:m"}}]{{c.user}}: </b><span> {{c.text}}</span>
            </div>
            {% endfor %}

app/templates/home/consultas/notificaciones_ind.html
<span class="noty-manager-bubble" style="margin-left: 11px; top: 10px; opacity: 1;">{{conteo_eventos_usuario}}</span>

app/templates/home/consultas/tolerancia.html
<div class="container" style="width:300px">

    <h4><b>Tolerancia</b></h4>
    <div id="notification" class="noty-manager-list-item noty-manager-list-item-warning">
        <div class="activity-item">
            <table class="table">
                <!--                     <th>Cliente</th>
            <th>A</th>
            <th>R</th>
            <th>V</th>
            -->
                    {% for c in en_tiempo %}
            <tr style="height: 25px;">
                <td> <b>{{c.1}}</b>
                </td>

                <td>
                    <span class="badge alert-success">{{c.3}}</span>
                </td>
                <td>
                    <span class="badge alert-warning">{{c.4}}</span>
                </td>
                <td>
                    <span class="badge alert-danger">{{c.5}}</span>
                </td>
                <td>
                    <span class="badge alert-default">{{c.2}}</span>
                </td>
            </tr>
            {%endfor%}
        </table>
    </div>
</div>
</div>