urls.py
from django.conf.urls import patterns, url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import login
from django.contrib import admin
from django.conf import settings
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.core.urlresolvers import reverse
from django.utils.functional import curry
from django.views.defaults import *
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from app.api import *
from tastypie.api import Api
from calendario.urls import *

admin.autodiscover()

v1_api = Api(api_name='v1')
v1_api.register(AvaluoResource())
v1_api.register(UserResource())
v1_api.register(DeptoResource())
v1_api.register(ImagenAvaluoResource())
v1_api.register(EstadisticoAsignaResource())
v1_api.register(EventoResource())
v1_api.register(EventoCalendarioResource())
v1_api.register(FacturaResource())
    # Examples:
    # url(r'^$', 'SIAV.views.home', name='home'),
    #url(r'^SIAV/', include('SIAV.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:

    # Upload files Urls

handler404 = 'app.views.handler404'
handler500 = 'app.views.handler500'
handler401 = 'app.views.handler401'
urlpatterns = patterns(


    '', url(r'^SIAV/ajax_upload/(\w*\d+)/(\@*\w*\d+)/$', 'app.uploads.ajax_upload', name="ajax_upload"),

    url(r'^oauth2/', include('provider.oauth2.urls', namespace = 'oauth2')),
    #url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^api/', include(v1_api.urls)),
    url(r'^SIAV/admin/', include(admin.site.urls)),



    #Urls del SIAV

    url(r'^SIAV/$', 'app.views.home', name='home'),
    url(r'^SIAV/login/$',  login),
    url(r'^SIAV/logout/$', 'app.views.logout_view', name='logout_view'),
    url(r'^SIAV/home/$', 'app.views.home', name='home'),


    url(r'^SIAV/cambia_estatus/(?P<match>.+)/$', 'app.views.cambia_estatus', name='cambia_estatus'),

    #url(r'^$', 'app.views.lista_avaluo', name = 'lista_avaluo'),
    url(r'^SIAV/guarda_master/?(\d+)/?$', 'app.views.guarda_master', name='guarda_master'),
    url(r'^SIAV/consulta_master/', 'app.views.consulta_master', name='consulta_master'),
    url(r'^SIAV/consulta_master/(?P<query>)/?$', 'app.views.consulta_master', name='consulta_master'),

    #Consulta de comparables
    url(r'^SIAV/consulta_comparable/$', 'app.views.consulta_comparable', name='consulta_comparable'),
    url(r'^SIAV/consulta_comparable/(?P<query>)/?$', 'app.views.consulta_comparable', name='consulta_comparable'),


    #url(r'^SIAV/consulta_sencilla/', 'app.views.consulta_sencilla', name='consulta_sencilla'),
    url(r'^SIAV/respuesta_consulta_sencilla/?(\d+)/?$', 'app.views.respuesta_consulta_sencilla', name='respuesta_consulta_sencilla'),

    url(r'^SIAV/alta_avaluo/$', 'app.views.alta_avaluo', name='alta_avaluo'),
    url(r'^SIAV/alta_avaluo_paquete/$', 'app.views.alta_avaluo_paquete', name='alta_avaluo_paquete'),
    url(r'^SIAV/actualiza_avaluo/(\d+)/$', 'app.views.actualiza_avaluo', name='actualiza_avaluo'),

    url(r'^SIAV/visita/$', 'app.views.visita', name='visita'),
    url(r'^SIAV/edita_visita/(\d+)/$', 'app.views.edita_visita', name='edita_visita'),

    #Url para eventos masivos
    url(r'^SIAV/visita_masiva/$', 'app.views.visita_masiva', name='visita_masiva'),
    url(r'^SIAV/captura_masiva/$', 'app.views.captura_masiva', name='captura_masiva'),
    url(r'^SIAV/salida_masiva/$', 'app.views.salida_masiva', name='salida_masiva'),

    url(r'^SIAV/show_visita_pdf/(\d+)/$', 'app.views.show_visita_pdf', name='show_visita_pdf'),
    url(r'^SIAV/show_orden_visita/$', 'app.views.show_orden_visita', name='show_orden_visita'),
    url(r'^SIAV/show_orden_visita/(?P<avaluo_visitado>)/?$', 'app.views.show_orden_visita', name='show_orden_visita'),

    url(r'^SIAV/captura/$', 'app.views.captura', name='captura'),

    #Salida
    url(r'^SIAV/salida/$', 'app.views.salida', name='salida'),
    url(r'^SIAV/edita_salida/(\d+)/$', 'app.views.edita_salida', name='edita_salida'),
    #url(r'^SIAV/salida_efectiva/(\d+)/$', 'app.views.salida_efectiva', name='salida_efectiva'),

    #Alta Usuario
    url(r'^SIAV/alta_usuario/$', 'app.views.alta_usuario', name='alta_usuario'),
    url(r'^SIAV/lista_usuario/$', 'app.views.lista_usuario', name='lista_usuario'),

    url(r'^SIAV/lista_valuador/$', 'app.views.lista_valuador', name='lista_valuador'),

    url(r'^SIAV/mapas/$', 'app.views.mapas', name='mapas'),

    url(r'^SIAV/facturar/$', 'app.views.facturar', name='facturar'),

    url(r'^SIAV/liquidar/$', 'app.views.liquidar', name='liquidar'),

    url(r'^SIAV/estadistico_anio_js/$', 'app.views.estadistico_anio_js', name='estadistico_anio_js'),
    url(r'^SIAV/estadistico/(\d+)/(\d+)/$', 'app.views.estadistico', name='estadistico'),
    url(r'^SIAV/estadistico_cliente_depto/(\d+)/(\d+)/$', 'app.views.estadistico_cliente_depto', name='estadistico_cliente_depto'),
    #url(r'^SIAV/estadistico/', 'app.views.estadistico', name = 'estadistico'),
    url(r'^SIAV/realtime/$', 'app.views.realtime', name = 'realtime'),

    #url(r'^SIAV/submitted/', 'app.views.submitted', name='submitted'),

    url(r'^SIAV/test/$', 'app.views.test', name='submitted'),

    url(r'^api/get_colonias/$', 'app.views.get_colonias', name='get_colonias'),
    url(r'^api/get_municipios/$', 'app.views.get_municipios', name='get_municipios'),
    url(r'^api/get_deptos/$', 'app.views.get_deptos', name='get_deptos'),
    url(r'^api/get_visitadores/$', 'calendario.views.get_visitadores', name='get_visitadores'),

    url(r'^SIAV/media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    #url(r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': '/static/img/favicon.ico'}),

    #Url para eliminar imagen
    url(r'^SIAV/elimina_imagen_captura/(\d+)/(\d+)/$', 'app.views.elimina_imagen_captura', name='elimina_imagen_captura'),

    #Urls del sitio web
    url(r'^$', 'website.views.index', name='index'),
    url(r'^faq/$', 'website.views.faq', name='faq'),
    url(r'^servicios/$', 'website.views.servicios', name='servicios'),
    url(r'^contacto/$', 'website.views.contacto', name='contacto'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'media/'}),

    #Urls del sitio movil
    #url(r'^SIAV/mobile/', 'app.views.mobile', name='mobile'),

    url(r'^swf/', 'app.views.swf', name='swf'),
)

    #Urls para sockets
urlpatterns += patterns('',
    url(r'^SIAV/chat/', 'websock.views.home', name='home'),
    url(r'^get_notificaciones/', 'websock.views.get_notificaciones', name='get_notificaciones'),
    url(r'^get_tolerancia/', 'websock.views.get_tolerancia', name='get_tolerancia'),
    url(r'^get_proceso/', 'websock.views.get_proceso', name='get_proceso'),
    url(r'^notificaciones_ind/', 'websock.views.notificaciones_ind', name='notificaciones_ind'),
    url(r'^get_conversaciones/', 'websock.views.get_conversaciones', name='get_conversaciones'),
    url(r'^chat_leido/(\d+)/$', 'websock.views.chat_leido', name='chat_leido'),

    #url(r'^marca_leidos/', 'websock.views.marca_leidos', name='marca_leidos'),
    url(r'^node_api$', 'websock.views.node_api', name='node_api'),

    url(r'^monto_inline/', 'app.views.inline.monto_inline', name='monto_inline'),
    url(r'^factura_inline/', 'app.views.inline.factura_inline', name='factura_inline'),
    url(r"^SIAV/calendario/", include("calendario.urls")),

    #Urls de calendario
    #url(include(r'^calendario/',calendario.urls)),
)


# Add the static files pattern to the url.
urlpatterns += staticfiles_urlpatterns() 
# handler404 = 'app.views.errors.not_found_error'

ficha/models.py
from django.db import models
from django.contrib.auth.models import User
from app.models import *
import os


# Create your models here.
class Ficha_Tecnica(models.Model):
    folio = models.IntegerField(primary_key=True)
    folio_2 = models.IntegerField(null=True,blank=True,default=None)
    municipio = models.ForeignKey(Municipio)
    region =  models.IntegerField(null=True,blank=True)
    colonia = models.CharField(null=True,blank=True, max_length=255)
    lote_tipo = models.CharField(null=True,blank=True, max_length=255)
    valuador = models.ForeignKey(User, null=True)
    LatitudG = models.DecimalField(null=True, max_digits=12, decimal_places=3)
    LatitudM = models.DecimalField(null=True, max_digits=12, decimal_places=3)
    LatitudS = models.DecimalField(null=True, max_digits=12, decimal_places=3)
    LongitudG = models.DecimalField(null=True, max_digits=12, decimal_places=3)
    LongitudM = models.DecimalField(null=True, max_digits=12, decimal_places=3)
    LongitudS = models.DecimalField(null=True, max_digits=12, decimal_places=3)
    limite_norte = models.CharField(null=True,blank=True, max_length=255)
    limite_sur = models.CharField(null=True,blank=True, max_length=255)
    limite_oriente = models.CharField(null=True,blank=True, max_length=255)
    limite_poniente = models.CharField(null=True,blank=True, max_length=255)
######################################################################################
    servicio_1 = models.CharField(null=True,blank=True, max_length=255)
    servicio_2 = models.CharField(null=True,blank=True, max_length=255)
    servicio_3 = models.CharField(null=True,blank=True, max_length=255)
    condicion = models.CharField(null=True,blank=True, max_length=255)
    equipamiento = models.CharField(null=True,blank=True, max_length=255)
    uso_suelo = models.CharField(null=True,blank=True, max_length=255)
    socioeconomico = models.CharField(null=True,blank=True, max_length=255)
    calidad = models.CharField(null=True,blank=True, max_length=255)
    niveles = models.CharField(null=True,blank=True, max_length=255)
    densidad = models.CharField(null=True,blank=True, max_length=255)
    entorno_urbano_1 = models.CharField(null=True,blank=True, max_length=255)
    entorno_urbano_2 = models.CharField(null=True,blank=True, max_length=255)
    riesgo_1 = models.CharField(null=True,blank=True, max_length=255)
    riesgo_2 = models.CharField(null=True,blank=True, max_length=255)
    valor_propuesto = models.CharField(null=True,blank=True,default=None, max_length=255)
    observaciones =  models.CharField(null=True,blank=True,default=None, max_length=255)
    factor = models.DecimalField(null=True,blank=True,default=None, max_digits=12, decimal_places=2)

    def __unicode__(self):
        if self.folio is None:
            return "N/D"
        else:
            return '%s' % self.folio

class Investigacion_Mercado(models.Model):
    investigacion_id = models.AutoField(primary_key=True)
    ficha_id = models.ForeignKey(Ficha_Tecnica)
    calle = models.CharField(null=True, max_length=255)
    colonia = models.CharField(null=True, max_length=255)
    fuente = models.CharField(null=True, max_length=255)
    telefono = models.CharField(null=True, max_length=255)
    uso = models.CharField(null=True, max_length=255)
    m_terreno = models.CharField(null=True, max_length=255)
    m_construccion = models.CharField(null=True, max_length=255)
    oferta = models.DecimalField(null=True, max_digits=12, decimal_places=2)
    unitario_0 = models.DecimalField(null=True, max_digits=12, decimal_places=2)
    unitario = models.DecimalField(null=True, max_digits=12, decimal_places=2)
    factor = models.DecimalField(null=True, max_digits=12, decimal_places=2)

    def __unicode__(self):
        if self.investigacion_id is None:
            return "N/D"
        else:
            return '%s' % self.investigacion_id

class Valores_Unitarios(models.Model):
    valores_id = models.AutoField(primary_key=True)
    ficha_id = models.ForeignKey(Ficha_Tecnica)
    valor_operacion = models.DecimalField(null=True, max_digits=12, decimal_places=2)
    valor_mercado = models.DecimalField(null=True, max_digits=12, decimal_places=2)
    activo = models.CharField(null=True, max_length=255)
    def __unicode__(self):
        if self.valores_id is None:
            return "N/D"
        else:
            return '%s' % self.valores_id

def get_image_path(folder, filename):
    return os.path.join('media/',str(folder), filename)

class ImagenFicha(models.Model):
    imagen_id = models.AutoField(primary_key=True)
    folio = models.CharField(null=True, max_length=255)
    ficha = models.ForeignKey(Ficha_Tecnica)
    imagen = models.ImageField("Imagen Ficha", upload_to=get_image_path, blank=True, null=True)

    def __unicode__(self):
        return unicode(self.folio)

class ArchivoFicha(models.Model):
    archivo_id = models.AutoField(primary_key=True)
    folio = models.CharField(null=True, max_length=255)
    ficha = models.ForeignKey(Ficha_Tecnica)
    file = models.FileField("Archivo Ficha", upload_to=get_image_path, blank = True, null=True)

    def __unicode__(self):
        return unicode(self.folio)

app/views/reports.py
# -*- coding: utf-8 -*-
from app.models import Avaluo
from django.template import RequestContext
from django.template.loader import render_to_string
from django.http import HttpResponse,HttpResponseNotFound
from django.shortcuts import render_to_response, redirect

def genera_foliok(avaluo_id,colonia):
    if(len(colonia.split()) > 1):
        primera = colonia.split()[0]
        ultima = colonia.split()[-1]

        folio_k = ultima[:2] + primera[:1] + str(avaluo_id)
        return folio_k
    elif(len(colonia.split()) == 1):
        primera = colonia.split()[0]
        ultima = colonia.split()[-1]

        folio_k =primera[:3] + str(avaluo_id)    
        return folio_k
    else:
        folio_k = ""
        return folio_k



def show_orden_visita(request):
    lista_visitado = request.GET.getlist('avaluo_visitado')
    avaluos_visitados = Avaluo.objects.filter(FolioK__in=lista_visitado)
    avaluo = avaluos_visitados[0]
    return render_to_response('reports/orden_visita.html',{'avaluo':avaluo,'avaluos_visitados':avaluos_visitados}, context_instance=RequestContext(request))

def show_visita_pdf(request, id):
    avaluo= Avaluo.objects.get(pk=id)

    colonia = avaluo.Colonia
    avaluo_id = avaluo.avaluo_id
        
    folio_k = genera_foliok(avaluo_id,colonia)

    if(avaluo.Tipo_id == 1):
        return render_to_response('reports/visita_terreno.html',{'folio_k':folio_k,'avaluo':avaluo}, context_instance=RequestContext(request))
    elif(avaluo.Tipo_id == 2):
        return render_to_response('reports/visita_casa.html',{'folio_k':folio_k,'avaluo':avaluo}, context_instance=RequestContext(request))
    elif(avaluo.Tipo_id == 3):
        return render_to_response('reports/visita_casa.html',{'folio_k':folio_k,'avaluo':avaluo}, context_instance=RequestContext(request))
    elif(avaluo.Tipo_id == 4):
        return render_to_response('reports/visita_nave.html',{'folio_k':folio_k,'avaluo':avaluo}, context_instance=RequestContext(request))
    elif(avaluo.Tipo_id == 5):
        return render_to_response('reports/visita_nave.html',{'folio_k':folio_k,'avaluo':avaluo}, context_instance=RequestContext(request))
    elif(avaluo.Tipo_id == 6):
        return render_to_response('reports/visita_nave.html',{'folio_k':folio_k,'avaluo':avaluo}, context_instance=RequestContext(request))
    else:
        return HttpResponseNotFound('<h1>No se encontró el reporte.</h1>')

templates/home/ficha/reports/ficha1.html
{% load round_hunded %}

<html>
<head>
	<style type="text/css">
	td,th {
		text-align: center;
		font-family: arial;
		font-size:75%
	}
	td li {
		text-align: left;
	}
	li { list-style:none; }
	ul { padding:0px; }
	body { margin: 5cm 0px 0px 0.9cm; }
	td.dark{
		background-color: #151515;
		color: #FFFFFF;
		font-family: arial;
		font-weight:bold;
		font-size:75%

	}
	td.gray{
		background-color: #D8D8D8;
		color: #000000;
		font-family: arial;
		font-size:75%

	}

	.checkboxes label
	{
		display: block;
		float: left;
		padding-right: 10px;
		white-space: nowrap;
	}

	.checkboxes input
	{
		vertical-align: middle;
	}

	.checkboxes label span
	{
		vertical-align: middle;
	}
	.blackEdge {

		border:1;
   	    border-spacing:0;
        border-collapse:collapse;
		border-color:000000;
	}

	</style>
	<script type="text/javascript" language="javascript" src="{{ STATIC_URL }}JS/jquery-1.8.2.min.js"></script>
	<script type="text/javascript" language="javascript" src="{{ STATIC_URL }}JS/autoNumeric.js"></script>
	<script type="text/javascript">


function roundHundred(value){
   return Math.round(value/100)*100
}

	$(document).ready(function(){
	  $('.oferta').autoNumeric('init', {aSign: '$',"mDec":2 });
	  $('.unitario').autoNumeric('init', {aSign: '$',"mDec":2 });
	  $('.unitario').autoNumeric('init', {aSign: '$',"mDec":2 });
	});




	</script>

	
</head>
<body>
	<table border="1" cellspacing=0 cellpadding=2 bordercolor="000000" width="700px">
		<tr >
			<td colspan="4" class="dark">
				FICHA TÉCNICA DE VALUACIÓN
			</td>
		</tr>
		<tr >
			<td colspan="3" style="text-align:right">
				<div class="fieldWrapper">
					{{ form.subject.errors }}
					<label for="id_folio"><b>Folio No.</b></label>		        
				</div>
			</td>
			<td>
				{{ ficha.folio }}
			</td>
		</tr>
		<tr>
			<td class="dark" colspan="4">UBICACIÓN</td>
		</tr>
		<tr>
			<td class="gray">
				<div class="fieldWrapper">
					{{ form.subject.errors }}
					<label for="id_region">Región:</label>		        
				</div>
			</td>
			<td>
				{{ ficha.region }}
			</td>
			<td class="gray">
				<div class="fieldWrapper">
					{{ form.subject.errors }}
					<label for="id_colonia">Colonia:</label>		        
				</div>
			</td>
			<td>
				{{ ficha.colonia }}
			</td>
		</tr>
		<tr>
			<td class="gray">
				<div class="fieldWrapper">
					{{ form.subject.errors }}
					<label for="id_limite_norte">Limite Norte:</label>		        
				</div>
			</td>
			<td class="gray">
				<div class="fieldWrapper">
					{{ form.subject.errors }}
					<label for="id_limite_sur">Limite Sur:</label>

				</div>
			</td>
			<td class="gray">
				<div class="fieldWrapper">
					{{ form.subject.errors }}
					<label for="id_limite_oriente">Limite Oriente:</label>

				</div>
			</td>
			<td class="gray">
				<div class="fieldWrapper">
					{{ form.subject.errors }}
					<label for="id_limite_poniente">Limite Poniente:</label>

				</div>
			</td>
			<tr>
				<td width="25%">
					{{ ficha.limite_norte }}
				</td>
				<td width="25%">
					{{ ficha.limite_sur }}
				</td>
				<td width="25%">
					{{ ficha.limite_oriente }}
				</td>
				<td width="25%">
					{{ ficha.limite_poniente }}
				</td>
			</tr>
			<tr>
				<td class="dark" colspan="3">
					SERVICIOS PÚBLICOS E INFRAESTRUCTURA
				</td>
				<td class="dark" >
					EQUIPAMIENTO URBANO
				</td>
			</tr>
			<tr>
				<td>
					<div class="controls">
						{{ form.servicio_1 }}
					</div>
				</td>
				<td>
					{{ form.servicio_2 }}
				</td>
				<td>
					{{ form.servicio_3 }}
				</td>
				<td>
					{{ form.equipamiento }}
				</td>
			</tr>
			<tr>
				<td class="dark" colspan="4">
					USO DEL SUELO
				</td>	
			</tr>
			<tr>
				<td  colspan="4">
					<div class="checkboxes">
						{{ form.uso_suelo }}
					</div>
				</td>
			</tr>
			<!-- <tr>
				<td colspan="3">
					SEGÚN PLAN DE DESARROLLO URBANO
				</td>
			</tr>
			<tr>
				<td class="dark" colspan="2">
					NIVEL SOCIOECONÓMICO
				</td>
				<td class="dark" colspan="2">
					CALIDAD DE LA CONSTRUCCIÓN
				</td>
			</tr>
			<tr>
				<td colspan="2">
					<div class="checkboxes">
						{{ form.socioeconomico }}
					</div>
				</td>
				<td colspan="2">
					<div class="checkboxes">
						{{ form.calidad }}
					</div>
				</td>				
			</tr> -->
<!-- 			<tr >
				<td class="dark">
					<div   class="fieldWrapper">
						{{ form.subject.errors }}
						<label for="id_limite_oriente">No. De Niveles</label> 
					</div>
				</td>
				<td colspan="3">
					<div class="checkboxes">
						{{ form.niveles }}
					</div>
				</td>
			</tr> -->
			<tr>
				<td class="dark" colspan="2">
					CARACTERÍSTICAS DEL ENTORNO URBANO
				</td>
				<td class="dark" colspan="2">
					FACTORES DE RIESGO
				</td>										
			</tr>
			<tr>
				<td>
					{{ form.entorno_urbano_1 }}
				</td>
				<td >
					{{ form.entorno_urbano_2 }}
				</td>
				<td>
					{{ form.riesgo_1 }}
				</td>
				<td >
					{{ form.riesgo_2 }}
				</td>
			</tr>
	</table>
	<table border="1" cellspacing=0 cellpadding=2 bordercolor="000000" width="700px" margin-top="15px">
		<tr>
				<td class="dark" colspan="5" >
					INVESTIGACIÓN DE MERCADO
				</td>
			</tr>
			<tr>
				<td class="gray">
					REFERENCIA
				</td>	
				<td class="gray">
					USO SUELO
				</td>
				<td class="gray">
					M.TERR.
				</td>
				<td class="gray">
					VALOR OFERTA
				</td>
				<td class="gray">
					VALOR VENTA
				</td>				
			</tr>
			{% for im in im_formset %}
			<tr>
				<td>	
					{{im.calle}}
				</td>		
				<td>	
					{{im.uso}}
				</td>
				<td>
					<label class="area">
						{{im.m_terreno}}
					</label>
				</td>
				<td>	
					<label class="oferta">
						{{im.oferta|default_if_none:"0.00" }}
					</label>
				</td>
				<td>
					<label class="oferta">
						'0.00'
					</label>
				</td>
			</tr>			
			{% endfor %}

		</tr>

	</table>
	<table  border="1" cellspacing=0 cellpadding=2 bordercolor="000000" width="700px">
		<tr>
			<td class="gray">
				VALORES UNITARIOS DE SUELO DE OPERACIONES REALIZADAS
			</td>
			<td class="gray">
				VALORES UNITARIOS DE SUELO DE SEGUN MERCADOS
			</td>
		</tr>
			{% for vu in vu_formset %}
			<tr>
				<td>
					<label class="oferta">
					{% if ficha.municipio_id == 978 %}	
						{{vu.valor_operacion|round_hunded_10|default_if_none:"0.00" }}
					{% else %}
						{{vu.valor_operacion|round_hunded|default_if_none:"0.00" }}
					{% endif %}
					</label>
				</td>		
				<td>
					<label class="oferta">
					{% if ficha.municipio_id == 978 %}	
						{{vu.valor_mercado|round_hunded_10|default_if_none:"0.00" }}
					{% else %}
						{{vu.valor_mercado|round_hunded|default_if_none:"0.00" }}
					{% endif %}
					</label>
				</td>
			</tr>			
			{% endfor %}



	</table>
	<br>
		<label style="margin-left:120px;"><b>Valor propuesto resultante: 
			<u><label class="oferta">
				{% if ficha.folio == 44 %}
					{{ficha.valor_propuesto}}
				{% else %}
					{% if ficha.municipio_id == 978 %}
						{{ficha.valor_propuesto|round_hunded_10}}
					{% else %}
						{{ficha.valor_propuesto|round_hunded}}
					{% endif %}
				{% endif %}
			</label>
		 m2 </u> *Según datos de la ficha</b>
	</label>
		{% for item in imagenes %}

		<table style="width:654px" cellspacing=0 cellpadding=2>
			   {% if not forloop.counter|divisibleby:2 %}
			   		<br>
					<br>
					<br>
					<br>
					<br>
					<br>
					<br>
					<br>
					<br>
					<br>
					<br>
			   	<tr>
					<td class="dark" colspan="4">REPORTE FOTOGRÁFICO &nbsp&nbsp - &nbsp&nbsp FICHA {{ficha.folio}}</td>
				</tr>
    			{% endif %}
			<tr>
			<br>
			<br>
			<br>
			<br>
				<td>
					<img src="/{{item.imagen}}" style="width:400;height:300"/>
				</td>
			</tr>	
		</table>		
		{% endfor %}




</body>
</html>